In [31]:
import numpy as np
import scipy.stats
import pandas as pd

## Problem 2

In [32]:
df = pd.read_csv(r'data/T5-2.dat', names=['test1', 'test2', 'test3'], sep='\s+')
df.head()

test1  test2  test3
0    468     41     26
1    428     39     26
2    514     53     21
3    547     67     33
4    614     61     27

### Problem 2 (a)

In [33]:
n, p = df.shape
xbar = np.mean(df.values, axis=0).reshape(-1, 1)
S = np.cov(df.values.T)

print(f'{n = }', f'{p = }', f'xbar = {xbar}', f'S = {S}', sep='\n')

n = 87
p = 3
xbar = [[526.5862069 ]
 [ 54.68965517]
 [ 25.12643678]]
S = [[5808.05934242  597.83520449  222.02967121]
 [ 597.83520449  126.05372895   23.38853248]
 [ 222.02967121   23.38853248   23.11173483]]


### Problem 2 (b)

In [34]:
mu = np.array([525, 52, 25]).reshape(-1, 1)
alpha = 0.05

T2 = (n * (xbar-mu).T @ np.linalg.inv(S) @ (xbar-mu)).reshape(-1)[0]
f_stat = ((n-p)*T2) / ((n-1)*p)

pp = scipy.stats.f.ppf(1-alpha, p, n-p)

print(f'T2 = {T2:.6f}', f'f_stat = {f_stat:.6f}', f'pp = {pp:.6f}', sep='\n')

T2 = 8.656460
f_stat = 2.818382
pp = 2.713227


In [35]:
k = ((n-1)*p*pp) / (n*(n-p))

print(f'k = {k:.6f}')

k = 0.095787


### Problem 2 (d)

In [36]:
Lambda, u = np.linalg.eig(S)

print(f'Lambda = {np.diag(Lambda)}', f'u = {u}', f'axes lengths = {np.sqrt(k*Lambda)}', sep='\n')

Lambda = [[5878.79164939    0.            0.        ]
 [   0.           63.83509965    0.        ]
 [   0.            0.           14.59805717]]
u = [[-0.99390539 -0.10373153 -0.0373074 ]
 [-0.10344339  0.99458923 -0.00957782]
 [-0.03809906  0.00566024  0.99925794]]
axes lengths = [23.72999755  2.47276833  1.18250011]


### Problem 2 (e)

In [37]:
alpha_star = alpha/p

for i in range(xbar.shape[0]):
    center = xbar[i][0]
    width = scipy.stats.t.ppf(1-alpha_star/2, n-1) * (S[i, i]/n)**0.5
    print(f'R{i+1} = ({center-width:.6f}, {center+width:.6f})')

R1 = (506.635889, 546.536524)
R2 = (51.750570, 57.628740)
R3 = (23.867944, 26.384929)


## Problem 3

### Problem 3 (a)

In [38]:
alpha = 0.01
p = 2

xbar = np.mean(df.values[:, [0,2]], axis=0).reshape(-1, 1)
S = np.cov(df.values[:, [0,2]].T)

mu = np.array([525, 25]).reshape(-1, 1)
alpha = 0.01

T2 = (n * (xbar-mu).T @ np.linalg.inv(S) @ (xbar-mu)).reshape(-1)[0]
pp = scipy.stats.chi2.ppf(1-alpha, 2)

print(f'S = {S}', f'T2 = {T2:.6f}', f'pp = {pp:.6f}', sep='\n')

S = [[5808.05934242  222.02967121]
 [ 222.02967121   23.11173483]]
T2 = 0.063446
pp = 9.210340


In [39]:
pp / n

0.10586598128708254

### Problem 3 (c)

In [40]:
alpha_star = alpha/p

for i in range(xbar.shape[0]):
    center = xbar[i][0]
    width = scipy.stats.norm.ppf(1-alpha_star/2) * (S[i, i]/n)**0.5
    print(f'R{2*i+1} = ({center-width:.6f}, {center+width:.6f})')

R1 = (503.650954, 549.521460)
R3 = (23.679651, 26.573223)


## Problem 4

In [41]:
df = pd.read_csv(r'data/T6-10.dat', names=['fuel', 'repair', 'capital', 'type'], sep='\s+')
df.head()

fuel  repair  capital      type
0  16.44   12.43    11.23  gasoline
1   7.19    2.70     3.92  gasoline
2   9.92    1.35     9.75  gasoline
3   4.24    5.78     7.78  gasoline
4  11.20    5.05    10.67  gasoline

### Problem 4 (a)

In [42]:
df_gasoline = df[df.type == 'gasoline'].drop(columns=['type'])
df_diesel = df[df.type == 'diesel'].drop(columns=['type'])

p, n_gasoline, n_diesel = df_gasoline.shape[1], df_gasoline.shape[0], df_diesel.shape[0]  

print(f'p = {p}', f'n_gasoline = {n_gasoline}', f'n_diesel = {n_diesel}', sep='\n')

p = 3
n_gasoline = 36
n_diesel = 23


In [43]:
xbar_gasoline = np.mean(df_gasoline.values, axis=0).reshape(-1, 1)
xbar_diesel = np.mean(df_diesel.values, axis=0).reshape(-1, 1)

print(f'xbar_gasoline = {xbar_gasoline}', f'xbar_diesel = {xbar_diesel}', sep='\n')

xbar_gasoline = [[12.21861111]
 [ 8.1125    ]
 [ 9.59027778]]
xbar_diesel = [[10.10565217]
 [10.76217391]
 [18.16782609]]


In [44]:
S_gasoline = np.cov(df_gasoline.values.T)
S_diesel = np.cov(df_diesel.values.T)

print(f'S_gasoline = {S_gasoline}', f'S_diesel = {S_diesel}', sep='\n')

S_gasoline = [[23.01336087 12.366395    2.90660897]
 [12.366395   17.54411071  4.77308214]
 [ 2.90660897  4.77308214 13.96333421]]
S_diesel = [[ 4.3623166   0.75988715  2.36209921]
 [ 0.75988715 25.85123597  7.68573221]
 [ 2.36209921  7.68573221 46.6543996 ]]


In [45]:
S_pool = ((n_gasoline-1)*S_gasoline+(n_diesel-1)*S_diesel) / (n_gasoline+n_diesel-2)
print(f'S_pool = {S_pool}')

S_pool = [[15.81471221  7.88669022  2.69644731]
 [ 7.88669022 20.75036958  5.89726287]
 [ 2.69644731  5.89726287 26.5809384 ]]


In [46]:
alpha = 0.01

T2 = ((xbar_gasoline-xbar_diesel).T @ np.linalg.inv(S_pool) @ (xbar_gasoline-xbar_diesel)).reshape(-1)[0] / (1/n_gasoline+1/n_diesel)
f_stat = (n_gasoline+n_diesel-2)*p / (n_gasoline+n_diesel-1-p) * scipy.stats.f.ppf(1-alpha, p, n_gasoline+n_diesel-1-p)

print(f'T2 = {T2:.6f}', f'f_stat = {f_stat:.6f}', sep='\n')

T2 = 50.912787
f_stat = 12.930960


### Problem 4 (b)

In [47]:
alpha_star = alpha/p

for i in range(xbar_gasoline.shape[0]):
    center = xbar_gasoline[i, 0] - xbar_diesel[i, 0]
    width = scipy.stats.t.ppf(1-alpha_star/2, n_gasoline+n_diesel-2)*((1/n_gasoline+1/n_diesel)*S_pool[i, i])**0.5
    print(f'R{i+1} = ({center-width:.6f}, {center+width:.6f})')

R1 = (-1.139584, 5.365502)
R2 = (-6.375352, 1.076004)
R3 = (-12.794295, -4.360802)


## Problem 5

In [48]:
df = pd.read_csv(r'data/T6-13.dat', names=['max_breadth', 'bb_height', 'bv_length', 'nasal_height', 'period'], sep='\s+')
df.head()

max_breadth  bb_height  bv_length  nasal_height  period
0          131        138         89            49       1
1          125        131         92            48       1
2          131        132         99            50       1
3          119        132         96            44       1
4          136        143        100            54       1

In [49]:
groups = [df[df.period == i].drop(columns=['period']) for i in sorted(pd.unique(df.period).tolist())]
p, G = df.shape[1] - 1, len(groups)
ns = [group.shape[0] for group in groups]
n = sum(ns)

print(f'p = {p}', f'G = {G}', sep='\n')

p = 4
G = 3


In [50]:
overall_mean = np.mean(df.values[:, :-1], axis=0).reshape(-1, 1)
groups_means = [np.mean(group.values, axis=0).reshape(-1, 1) for group in groups]

print(f'xbar = {overall_mean}')
print(*[f'xbar{i+1} = {groups_means[i]}' for i in range(G)], sep='\n')

xbar = [[132.73333333]
 [133.36666667]
 [ 98.08888889]
 [ 50.44444444]]
xbar1 = [[131.36666667]
 [133.6       ]
 [ 99.16666667]
 [ 50.53333333]]
xbar2 = [[132.36666667]
 [132.7       ]
 [ 99.06666667]
 [ 50.23333333]]
xbar3 = [[134.46666667]
 [133.8       ]
 [ 96.03333333]
 [ 50.56666667]]


In [51]:
B = sum([ni * (groupi_mean-overall_mean) @ (groupi_mean-overall_mean).T for ni, groupi_mean in zip(ns, groups_means)])

print(f'B = {B}')

B = [[ 150.2          20.3        -161.83333333    5.03333333]
 [  20.3          20.6         -38.73333333    6.43333333]
 [-161.83333333  -38.73333333  190.28888889  -10.85555556]
 [   5.03333333    6.43333333  -10.85555556    2.02222222]]


In [52]:
W = sum([(ni-1) * np.cov(groupi.values.T) for ni, groupi in zip(ns, groups)])

np.set_printoptions(suppress=True)
print(f'W = {W}', f'det(W) = {np.linalg.det(W)}', sep='\n')

W = [[1785.4         172.5         128.96666667  289.63333333]
 [ 172.5        1924.3         178.8         171.9       ]
 [ 128.96666667  178.8        2153.           -1.7       ]
 [ 289.63333333  171.9          -1.7         840.2       ]]
det(W) = 5669247218923.179


In [53]:
B_plus_W = B+W

print(f'B+W = {B_plus_W}', f'det(B+W) = {np.linalg.det(B+W)}', sep='\n')

B+W = [[1935.6         192.8         -32.86666667  294.66666667]
 [ 192.8        1944.9         140.06666667  178.33333333]
 [ -32.86666667  140.06666667 2343.28888889  -12.55555556]
 [ 294.66666667  178.33333333  -12.55555556  842.22222222]]
det(B+W) = 6829573414098.414


In [54]:
alpha = 0.05

Lambda = np.linalg.det(W) / np.linalg.det(B_plus_W)
stat = ((sum(ns)-p-2)/(p)) * ((1-Lambda**0.5)/(Lambda**0.5))
pp = scipy.stats.f.ppf(1-alpha, 2*p, 2*(sum(ns)-p-2))

print(f'stat = {stat:.6f}', f'pp = {pp:.6f}')

stat = 2.049069 pp = 1.993884


### Problem 5(b)

In [55]:
alpha_star = alpha / (p*G*(G-1)/2)

def pairwise_sci(j, k, l):
    return groups_means[l][j][0]-groups_means[k][j][0], scipy.stats.t.ppf(1-alpha_star/2, n-G) * ((1/ns[k]+1/ns[l]) * (W[j, j]/(n-G)))**0.5

for j in range(p):
    print(f'\nCOMPONENT {j+1}')
    for k in range(G):
        for l in range(k+1, G):
            center, width = pairwise_sci(j, k, l)
            print(f'\tGroup {k+1} and Group {l+1} - R = ({center-width:.6f}, {center+width:.6f})')


COMPONENT 1
	Group 1 and Group 2 - R = (-2.442312, 4.442312)
	Group 1 and Group 3 - R = (-0.342312, 6.542312)
	Group 2 and Group 3 - R = (-1.342312, 5.542312)

COMPONENT 2
	Group 1 and Group 2 - R = (-4.473706, 2.673706)
	Group 1 and Group 3 - R = (-3.373706, 3.773706)
	Group 2 and Group 3 - R = (-2.473706, 4.673706)

COMPONENT 3
	Group 1 and Group 2 - R = (-3.880110, 3.680110)
	Group 1 and Group 3 - R = (-6.913443, 0.646776)
	Group 2 and Group 3 - R = (-6.813443, 0.746776)

COMPONENT 4
	Group 1 and Group 2 - R = (-2.661423, 2.061423)
	Group 1 and Group 3 - R = (-2.328089, 2.394756)
	Group 2 and Group 3 - R = (-2.028089, 2.694756)
